package tracking

import (
	"time"
)

func getBuiltinRules() []ClassificationRule {
	return []ClassificationRule{
		{
			Name:        "auth_error",
			Priority:    100,
			StatusCodes: []int{401, 403},
			Keywords:    []string{"unauthorized", "forbidden", "invalid_api_key", "authentication"},
			Kind:        "auth",
			Level:       CredentialLevel,
			Cooldown:    5 * time.Minute,
			Retryable:   false,
			Suggestions: []string{
				"Check API key validity",
				"Verify credential configuration",
				"Contact provider if key should be valid",
			},
		},
		{
			Name:        "quota_error",
			Priority:    95,
			StatusCodes: []int{402, 429},
			Keywords:    []string{"quota", "insufficient", "balance", "exceeded", "credit"},
			Kind:        "quota",
			Level:       CredentialLevel,
			Cooldown:    0,
			Retryable:   false,
			Suggestions: []string{
				"Recharge account balance",
				"Upgrade quota limits",
				"Manual intervention required",
			},
		},
		{
			Name:        "rate_limit",
			Priority:    90,
			StatusCodes: []int{429},
			Keywords:    []string{"rate", "limit", "too many requests", "throttle"},
			Kind:        "rate_limit",
			Level:       ModelLevel,
			Cooldown:    15 * time.Minute,
			Retryable:   true,
			Suggestions: []string{
				"Wait and retry",
				"Reduce request frequency",
				"Use alternative credentials",
			},
		},
		{
			Name:        "timeout",
			Priority:    85,
			StatusCodes: []int{408, 504},
			Keywords:    []string{"timeout", "timed out", "deadline exceeded"},
			Kind:        "timeout",
			Level:       ModelLevel,
			Cooldown:    30 * time.Second,
			Retryable:   true,
			Suggestions: []string{
				"Retry with exponential backoff",
				"Check network connectivity",
				"Consider increasing timeout threshold",
			},
		},
		{
			Name:        "model_not_found",
			Priority:    80,
			StatusCodes: []int{404},
			Keywords:    []string{"model", "not found", "does not exist", "unavailable"},
			Kind:        "model_not_found",
			Level:       ModelLevel,
			Cooldown:    24 * time.Hour,
			Retryable:   false,
			Suggestions: []string{
				"Verify model name",
				"Check provider documentation",
				"Model may be deprecated",
			},
		},
		{
			Name:        "upstream_down",
			Priority:    75,
			StatusCodes: []int{502, 503},
			Keywords:    []string{"bad gateway", "service unavailable", "upstream", "maintenance"},
			Kind:        "upstream_down",
			Level:       ModelLevel,
			Cooldown:    1 * time.Minute,
			Retryable:   true,
			Suggestions: []string{
				"Provider experiencing issues",
				"Wait and retry",
				"Switch to alternative provider",
			},
		},
		{
			Name:        "network_error",
			Priority:    70,
			StatusCodes: []int{500, 501, 505, 506, 507, 508, 509, 510, 511},
			Keywords:    []string{"internal server error", "network", "connection"},
			Kind:        "network",
			Level:       ModelLevel,
			Cooldown:    2 * time.Minute,
			Retryable:   true,
			Suggestions: []string{
				"Transient network issue",
				"Retry after cooldown",
				"Check provider status page",
			},
		},
		{
			Name:        "content_filter",
			Priority:    65,
			StatusCodes: []int{400},
			Keywords:    []string{"content_filter", "content_policy", "safety", "moderation"},
			Kind:        "content_filter",
			Level:       RequestLevel,
			Cooldown:    0,
			Retryable:   false,
			Suggestions: []string{
				"Request triggered content filter",
				"Modify input to comply with policy",
				"Review provider content guidelines",
			},
		},
		{
			Name:        "invalid_request",
			Priority:    60,
			StatusCodes: []int{400},
			Keywords:    []string{"invalid", "bad request", "malformed", "parameter"},
			Kind:        "invalid_request",
			Level:       RequestLevel,
			Cooldown:    0,
			Retryable:   false,
			Suggestions: []string{
				"Check request parameters",
				"Verify input format",
				"Consult API documentation",
			},
		},
		{
			Name:        "context_length_exceeded",
			Priority:    55,
			StatusCodes: []int{400},
			Keywords:    []string{"context_length", "token", "too long", "max_tokens"},
			Kind:        "context_length",
			Level:       RequestLevel,
			Cooldown:    0,
			Retryable:   false,
			Suggestions: []string{
				"Reduce input length",
				"Use model with larger context window",
				"Split request into smaller chunks",
			},
		},
	}
}
